#!/bin/sh
#
# american fuzzy lop - Advanced Persistent Graphing
# -------------------------------------------------
#
# Written and maintained by Michal Zalewski <lcamtuf@google.com>
# Based on a design & prototype by Michael Rash.
#
# Copyright 2014, 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#


out_dir=$1
plot_file=$out_dir'/plot_data.trim'
echo "plot file is " $plot_file
./trimdata.py $out_dir

(cat <<_EOF_
set terminal png truecolor enhanced size 1000,300 butt


#set xdata time
#set timefmt '%s'
#set format x "%b %d\n%H:%M"
set tics font 'small'
unset mxtics
unset mytics

set grid xtics linetype 0 linecolor rgb '#e0e0e0'
set grid ytics linetype 0 linecolor rgb '#e0e0e0'
set border linecolor rgb '#50c0f0'
set tics textcolor rgb '#000000'
set key outside

set autoscale xfixmin
set autoscale xfixmax
set style line 1 dashtype 1 lc rgb "cyan" linewidth 3
set style line 2 dashtype 1 lc rgb "red" linewidth 3
set style line 3 dashtype 1 lc rgb "orange" linewidth 3
set style line 4 dashtype 1 lc  rgb "blue" linewidth 3

set terminal pdf dashed butt
set output "$out_dir/cov-trend.pdf"

plot '$plot_file' using 1 title 'p1' smooth bezier ls 1,\\
	'' using 2 title 'p2' smooth bezier ls 2,\\
	 ''  using 3 title 'p3' smooth bezier ls 3,\\
	 ''  using 4 title 'p4' smooth bezier ls 4

_EOF_
) | gnuplot 


